### ISSUE TITLE
Bunch of test failures on Windows 8 64-bit

### ISSUE THREAD

**Issue by nippoo** [kwikteam/phy#478]
```
================================== FAILURES ===================================

_______________________________ test_disk_store _______________________________

    def test_disk_store():

        dtype = np.float32
        sha = (2, 4)
        shb = (3, 5)
        a = np.random.rand(*sha).astype(dtype)
        b = np.random.rand(*shb).astype(dtype)

        def _assert_equal(d_0, d_1):
            """Test the equality of two dictionaries containing NumPy arrays."""
            assert sorted(d_0.keys()) == sorted(d_1.keys())
            for key in d_0.keys():
                ac(d_0[key], d_1[key])

        with TemporaryDirectory() as tempdir:
            ds = DiskStore(tempdir)

            ds.register_file_extensions(['key', 'key_bis'])
            assert ds.cluster_ids == []

            ds.store(3, key=a)
            _assert_equal(ds.load(3,
                                  ['key'],
                                  dtype=dtype,
                                  shape=sha,
                                  ),
                          {'key': a})
            loaded = ds.load(3, 'key', dtype=dtype, shape=sha)
            ac(loaded, a)

            # Loading a non-existing key returns None.
            assert ds.load(3, 'key_bis') is None
            assert ds.cluster_ids == [3]

            ds.store(3, key_bis=b)
            _assert_equal(ds.load(3, ['key'], dtype=dtype, shape=sha), {'key': a})
            _assert_equal(ds.load(3, ['key_bis'],
                                  dtype=dtype,
                                  shape=shb,
                                  ),
                          {'key_bis': b})
            _assert_equal(ds.load(3,
                                  ['key', 'key_bis'],
                                  dtype=dtype,
                                  ),
                          {'key': a.ravel(), 'key_bis': b.ravel()})
            ac(ds.load(3, 'key_bis', dtype=dtype, shape=shb), b)
            assert ds.cluster_ids == [3]

>           ds.erase([2, 3])

build\lib\phy\io\tests\test_store.py:133:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <phy.io.store.DiskStore object at 0x0000000015FC20F0>, clusters = [2, 3]

    def erase(self, clusters):
        """Delete some clusters from the store."""
        for cluster in clusters:
            for key in self._allowed_extensions:
                path = self._cluster_path(cluster, key)
                if not op.exists(path):
                    continue
                # Safety first: http://bit.ly/1ITJyF6
                self._check_extension(path)
                if self._is_cluster_file(path):
>                   os.remove(path)
E                   WindowsError: [Error 32] The process cannot access the file because it is being used by another proc
ess: 'c:\\users\\max\\appdata\\local\\temp\\tmpbdsdzw\\3.key'

build\lib\phy\io\store.py:262: WindowsError
_____________________________ test_script_parser ______________________________

    def test_script_parser():

        kwik_path = 'test'

        for cmd in ('cluster-manual', 'cluster-auto'):
>           assert _parse([cmd, kwik_path]).command == cmd

build\lib\phy\scripts\tests\test_phy_script.py:47:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
build\lib\phy\scripts\tests\test_phy_script.py:39: in _parse
    return _parse_args(args)[0]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = ['cluster-manual', 'test']

    def _parse_args(args):
        desc = sys.modules['phy'].__doc__
        epilog = dedent("""

        examples:
          phy -v                display the version of phy
          phy describe my_file.kwik
                                display information about a Kwik dataset
          phy cluster-auto my_file.kwik --num-clusters-start=100
                                run klustakwik on a dataset
          phy cluster-manual my_file.kwik
                                run the manual clustering GUI

        """)
        parser = Parser(description=desc, epilog=epilog,
                        formatter_class=CustomFormatter,
                        )

        # Allowed subcommands.
        commands = [
            'cluster-auto',
            'cluster-manual',
            'describe',  # describe a dataset
            # TODO:
            # 'notebook',  # start a new analysis notebook
            # 'detect-spikes',
        ]

        parser.add_argument('command',
                            choices=commands,
                            help='command to execute')

        parser.add_argument('file',
                            help='file to execute the command on')

        import phy
        parser.add_argument('--version', '-v',
                            action='version',
>                           version=phy.__version_git__,
                            help='print the version of phy')
E       AttributeError: 'module' object has no attribute '__version_git__'

build\lib\phy\scripts\phy_script.py:97: AttributeError
_______________________________ test_script_run _______________________________

    def test_script_run():

        with TemporaryDirectory() as tmpdir:

            # Create the test HDF5 file in the temporary directory.
            kwik_path = create_mock_kwik(tmpdir,
                                         n_clusters=n_clusters,
                                         n_spikes=n_spikes,
                                         n_channels=n_channels,
                                         n_features_per_channel=n_fets,
                                         n_samples_traces=n_samples_traces)

            with raises(RuntimeError):
                _call('phy')

            _call('phy -v')
            _call('phy -h')
>           _call('phy describe ' + kwik_path)

build\lib\phy\scripts\tests\test_phy_script.py:92:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = 'phy describe c:\\users\\max\\appdata\\local\\temp\\tmpugq0x5\\_test.kwik'

    def _call(cmd):
        ret = call(cmd.split(' '))
        if ret != 0:
>           raise RuntimeError()
E           RuntimeError

build\lib\phy\scripts\tests\test_phy_script.py:35: RuntimeError
_________________________________ test_ccg_0 __________________________________

    def test_ccg_0():
        spike_samples = [0, 10, 10, 20]
        spike_clusters = [0, 1, 0, 1]
        binsize = 1
        winsize_bins = 2 * 3 + 1

        c_expected = np.zeros((2, 2, 4))

        # WARNING: correlograms() is sensitive to the order of identical spike
        # times. This needs to be taken into account when post-processing the
        # CCGs.
        c_expected[1, 0, 0] = 1
        c_expected[0, 1, 0] = 0  # This is a peculiarity of the algorithm.

        c = correlograms(spike_samples, spike_clusters,
>                        binsize=binsize, winsize_bins=winsize_bins)

build\lib\phy\stats\tests\test_ccg.py:81:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

spike_samples = array([ 0, 10, 10, 20]), spike_clusters = array([0, 1, 0, 1])
cluster_order = None, binsize = 1, winsize_bins = 7

    def correlograms(spike_samples, spike_clusters,
                     cluster_order=None,
                     binsize=None, winsize_bins=None):
        """Compute all pairwise cross-correlograms among the clusters appearing
        in `spike_clusters`.

        Parameters
        ----------

        spike_samples : array-like
            Spike times in samples (integers).
        spike_clusters : array-like
            Spike-cluster mapping.
        cluster_order : array-like
            The list of unique clusters, in any order. That order will be used
            in the output array.
        binsize : int
            Number of time samples in one bin.
        winsize_bins : int (odd number)
            Number of bins in the window.

        Returns
        -------

        correlograms : array
            A `(n_clusters, n_clusters, winsize_samples)` array with all pairwise
            CCGs.

        Notes
        -----

        If winsize_samples is the (odd) number of time samples in the window
        then:

            winsize_bins = 2 * ((winsize_samples // 2) // binsize) + 1
            assert winsize_bins % 2 == 1

        For performance reasons, it is recommended to compute the CCGs on a subset
        with only a few thousands or tens of thousands of spikes.

        """

        spike_clusters = _as_array(spike_clusters)
        spike_samples = _as_array(spike_samples)
        if spike_samples.dtype == np.int64:
            spike_samples = spike_samples.astype(np.uint64)

>       assert spike_samples.dtype == np.uint64
E       assert dtype('int32') == <type 'numpy.uint64'>
E        +  where dtype('int32') = array([ 0, 10, 10, 20]).dtype
E        +  and   <type 'numpy.uint64'> = <type 'numpy.uint64'>
E        +    where <type 'numpy.uint64'> = np.uint64

build\lib\phy\stats\ccg.py:86: AssertionError
```

**Comment by rossant** [comment]
most of these come from KK2 being not correctly compiled no?

**Comment by nippoo** [comment]
I've removed the ones that fail when KK2 isn't correctly installed now! That's another issue.

**Comment by rossant** [comment]
thanks! but I'm confused because I've already fixed the remaining ones a few days ago...

**Comment by nippoo** [comment]
euhhhh. I have no idea I'm afraid. Where did you fix it? The last one I'm definitely still getting when I pull master..

**Comment by rossant** [comment]
all tests pass on my Windows machine, closing
