### ISSUE TITLE
cluster assigning error

### ISSUE THREAD

**Issue by zhuangjun1981** [kwikteam/phy#706]
When I was trying to assign clusters. I got the following error:

`17:24:22 [E] cli:37               An error has occurred (TypeError): <functools.partial object at 0x0000000005C33E58> is not a Python function`

**Comment by nippoo** [comment]
Hey, I think this was fixed in https://github.com/kwikteam/phy/pull/698. Have you updated to the latest master?

**Comment by zhuangjun1981** [comment]
I updated the master, it did not solve the problem. However, it seems to work after I updated my python and reinstalled phy. Thanks
